
spring:

  redis:
    host: 106.10.54.127
    port: 6379

  cloud:
    gateway:
      default-filters:
      - RouteLog
      routes:
      - id: after_route
        uri: https://reqres.in
        predicates:
        - Path=/users/1
        filters:
        - SetPath=/api/users/1
        # - RouteLog